---

- name: test
  gather_facts: false
  hosts: all
  vars:
    ansible_user: ubuntu
  become: yes
  tasks:
  - name: Wait for server 
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=60
        become: false
  - name: Install Nginx Web Server on Debian Family
    apt:
      name: nginx
      state: latest   
      update_cache: yes 
    
