#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - "${~auth_key1~}"
      - "${~auth_key2~}"
package_update: true
package_upgrade: false
packages:
 - vim
 - nginx
